#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RouteCardAndroid.Resource", IsApplication=true)]

namespace RouteCardAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::RouteCard.Resource.String.library_name = global::RouteCardAndroid.Resource.String.library_name;
			global::PerpetualMobile.Storage.Resource.String.library_name = global::RouteCardAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int grey = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int osram = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int phone_padding = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int phone_padding_button = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int phone_padding_title = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int phone_text_size_label = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int phone_text_size_list_item = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int phone_text_size_subtitle = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int phone_text_size_title = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int phone_text_size_widget = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int tablet_padding = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int tablet_padding_button = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int tablet_padding_title = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int tablet_text_size_label = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int tablet_text_size_list_item = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int tablet_text_size_subtitle = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int tablet_text_size_title = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int tablet_text_size_widget = 2131165198;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0004
			public const int buttonLogin = 2131361796;
			
			// aapt resource value: 0x7f0a0006
			public const int buttonScan = 2131361798;
			
			// aapt resource value: 0x7f0a0009
			public const int buttonSearch = 2131361801;
			
			// aapt resource value: 0x7f0a0003
			public const int editTextPassword = 2131361795;
			
			// aapt resource value: 0x7f0a0008
			public const int editTextSearchLotNumber = 2131361800;
			
			// aapt resource value: 0x7f0a0002
			public const int editTextUsername = 2131361794;
			
			// aapt resource value: 0x7f0a000a
			public const int listViewQueryResult = 2131361802;
			
			// aapt resource value: 0x7f0a0037
			public const int menuItemAbout = 2131361847;
			
			// aapt resource value: 0x7f0a0036
			public const int menuItemChangeUser = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int menuItemLogOffUser = 2131361845;
			
			// aapt resource value: 0x7f0a000b
			public const int scrollView = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int tableLayout1 = 2131361804;
			
			// aapt resource value: 0x7f0a0030
			public const int textViewCTPlan = 2131361840;
			
			// aapt resource value: 0x7f0a0023
			public const int textViewCTPlanTitle = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int textViewCTPlanValue = 2131361828;
			
			// aapt resource value: 0x7f0a0033
			public const int textViewCTQ = 2131361843;
			
			// aapt resource value: 0x7f0a0025
			public const int textViewCTQTitle = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int textViewCTQValue = 2131361830;
			
			// aapt resource value: 0x7f0a0029
			public const int textViewColor = 2131361833;
			
			// aapt resource value: 0x7f0a002b
			public const int textViewFacility = 2131361835;
			
			// aapt resource value: 0x7f0a0015
			public const int textViewFacilityTitle = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int textViewFacilityValue = 2131361814;
			
			// aapt resource value: 0x7f0a002f
			public const int textViewOperation = 2131361839;
			
			// aapt resource value: 0x7f0a001f
			public const int textViewOperationNumberTitle = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int textViewOperationNumberValue = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int textViewOperationTextTitle = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int textViewOperationTextValue = 2131361826;
			
			// aapt resource value: 0x7f0a0013
			public const int textViewPlantTitle = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int textViewPlantValue = 2131361812;
			
			// aapt resource value: 0x7f0a002e
			public const int textViewPosition = 2131361838;
			
			// aapt resource value: 0x7f0a001d
			public const int textViewPositionTitle = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int textViewPositionValue = 2131361822;
			
			// aapt resource value: 0x7f0a0011
			public const int textViewProductTitle = 2131361809;
			
			// aapt resource value: 0x7f0a0031
			public const int textViewProductType = 2131361841;
			
			// aapt resource value: 0x7f0a000f
			public const int textViewProductTypeTitle = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int textViewProductTypeValue = 2131361808;
			
			// aapt resource value: 0x7f0a0012
			public const int textViewProductValue = 2131361810;
			
			// aapt resource value: 0x7f0a002c
			public const int textViewProductionLevel = 2131361836;
			
			// aapt resource value: 0x7f0a0017
			public const int textViewProductionLevelTitle = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int textViewProductionLevelValue = 2131361816;
			
			// aapt resource value: 0x7f0a0034
			public const int textViewRPT = 2131361844;
			
			// aapt resource value: 0x7f0a0027
			public const int textViewRPTTitle = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int textViewRPTValue = 2131361832;
			
			// aapt resource value: 0x7f0a002d
			public const int textViewRoute = 2131361837;
			
			// aapt resource value: 0x7f0a0019
			public const int textViewRouteTitle = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int textViewRouteValue = 2131361818;
			
			// aapt resource value: 0x7f0a0005
			public const int textViewScanLotLabel = 2131361797;
			
			// aapt resource value: 0x7f0a0007
			public const int textViewSearchLotLabel = 2131361799;
			
			// aapt resource value: 0x7f0a0001
			public const int textViewSubTitle = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int textViewTitle = 2131361792;
			
			// aapt resource value: 0x7f0a002a
			public const int textViewType = 2131361834;
			
			// aapt resource value: 0x7f0a000d
			public const int textViewTypeTitle = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int textViewTypeValue = 2131361806;
			
			// aapt resource value: 0x7f0a0032
			public const int textViewVersion = 2131361842;
			
			// aapt resource value: 0x7f0a001b
			public const int textViewVersionTitle = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int textViewVersionValue = 2131361820;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Query = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int QueryResult = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int QueryResultDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int QueryResultItem = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int query_menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int beep = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int camera_swap_icon = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int camera_swap_icon_pressed = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int flashlight_turn_off_icon = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int flashlight_turn_off_icon_pressed = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int flashlight_turn_on_icon = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int flashlight_turn_on_icon_pressed = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ic_btn_search = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int poweredby2x = 2130968584;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int content_lot_number = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int content_password = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int content_username = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int label_enter_lot_number = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int label_login_button = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int label_scan_button = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int label_scan_lot_number = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int label_search_button = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int menu_item_label_about = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int menu_item_label_change_user = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int menu_item_label_log_off_user = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int subtitle_login_screen = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int title_login_screen = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int toast_login_error = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int toast_login_invalid = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int toast_lot_not_found = 2131034119;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Mono_Android_Theme_Splash = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
