#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RouteCardAndroid.Resource", IsApplication=true)]

namespace RouteCardAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::RouteCard.Resource.String.library_name = global::RouteCardAndroid.Resource.String.library_name;
			global::PerpetualMobile.Storage.Resource.String.library_name = global::RouteCardAndroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int phone_padding = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int phone_padding_button = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int phone_padding_title = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int phone_text_size_label = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int phone_text_size_list_item = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int phone_text_size_title = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int phone_text_size_widget = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int tablet_padding = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int tablet_padding_button = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int tablet_padding_title = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int tablet_text_size_label = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int tablet_text_size_list_item = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int tablet_text_size_title = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int tablet_text_size_widget = 2131034124;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int buttonLogin = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int buttonSearch = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int editTextLotNumber = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int editTextPassword = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int editTextUsername = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int listViewQueryResult = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int textViewArrivalDate = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int textViewArrivalTime = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int textViewFacility = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int textViewLotLabel = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int textViewOperation = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int textViewOperator = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int textViewProcessingTime = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int textViewProductionLevel = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int textViewRoute = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int textViewTitle = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Query = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int QueryResult = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int QueryResultDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int QueryResultItem = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040009
			public const int content_lot_number = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int content_password = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int content_username = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int label_login_button = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int label_lot_number = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int label_search_button = 2130968586;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int title_login_screen = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int toast_login_error = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int toast_login_invalid = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int toast_lot_not_found = 2130968587;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
